name: Local tests
description: Run unit tests and local integ tests

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  github-username:
    description: 'GitHub username for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out package
      uses: actions/checkout@v4
      with:
        # Specify repository so this action can be run from other repositories
        repository: On-Demand-Deletion-Platform/aws-data-deletion-worker
        path: aws-data-deletion-worker
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21
    - name: Run gradle build
      run: gradle wrapper build
      shell: bash
      working-directory: aws-data-deletion-worker
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_USERNAME: ${{ inputs.github-username }}
    - name: Run gradle localIntegTest
      run: gradle wrapper localIntegTest
      shell: bash
      working-directory: aws-data-deletion-worker
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_USERNAME: ${{ inputs.github-username }}
